### ISSUE TITLE
Navbar link to landing page

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#125]
We should add a link in the navbar that takes the client back to the client landing page - clicking on the Keep.id logo to return to the landing page is not intuitive. The same goes for the admin and the worker landing page.

![image](https://user-images.githubusercontent.com/28871950/97790299-d9091a80-1b9d-11eb-8240-2d8a0a1aa8fa.png)

**Comment by crchong1** [comment]
@vanessa-hu do you think you could take a look at this?

**Comment by vanessa-hu** [comment]
- home for [clients](https://www.figma.com/file/3Xf9AS2CPzYg6dUtyy046t/Client-Dashboard?node-id=70%3A870) and [workers](https://www.figma.com/file/QoO9Twx6lyL722ZEjHhGYm/Worker-Landing-Page)
- currently /home for admins is just [my clients](https://www.figma.com/file/PpjMYAJWjnZBmYlx71jHah/Admin-Panel?node-id=0%3A1) might be dashboard later
- will just title it Home except for Role.Admin for now (My Clients)

**Comment by scye09** [comment]
@vanessa-hu Is this currently deployed in the public website? I don't see a Home tab in the navbar when I log in as a client

![image](https://user-images.githubusercontent.com/28871950/100287482-b7077b80-2f42-11eb-8b82-22fff4fd1597.png)

**Comment by vanessa-hu** [comment]
@scye09 Hmm, I'm a little confused because it shows up for me. Maybe someone merged their branch and overwrote mine? @crchong1 
![image](https://user-images.githubusercontent.com/21111373/100549720-ba507f00-3242-11eb-96a3-18535d95c142.png)
![image](https://user-images.githubusercontent.com/21111373/100549730-c2a8ba00-3242-11eb-9901-ddb1839268fc.png)
