### ISSUE TITLE
Table Component Implementation Epic

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#130]
### To Dos:
Figma link: https://www.figma.com/file/0ZahIADAc8HwkI55P8IKlU/Tables?node-id=0%3A1 

### Edit and Delete 
Edit and Delete and Save Functionality #131 
Edit and Delete and Save button Styling (including icons) #132 
Edit and Delete and Save column toggling #133 

### General Styling
Text and Spacing Styling (found under general guidelines) #134 
Zebra shading on tables > 10 results #135 
Empty Table Styling #136 
Empty Table Button variable text #137 
Empty Table event listener to trigger parent on empty table button press #138 
On Hover mouse and also tab navigation styling #139 

### Checkboxes
Adding checkbox #140
Adding highlighting of entire row for checkbox #141
Adding a state to indicate which rows have been selected #142 

### Bottom Bar
Showing x of x results functionality and styling #143 
x results per page functionality and styling #144 
pagination + pagination styling #145

**Comment by loafyyy** [comment]
I think highlighting stuff should be one feature (on checkbox click, on hover, on edit, etc. because I think the implementation will be similar). The checkbox feature should just be to create the row of checkboxes, which I don't think will be that hard.

Edit and Delete button Styling (including icons) => Edit, delete, and save

Everything else looks good I think. Some stuff I already did like basic edit functionality but delete functionality has not been implemented on the frontend.

**Comment by loafyyy** [comment]
Also, we need empty table styling.

**Comment by crchong1** [comment]
I will just include a link in each ticket to refer to each other, instead of making them all one ticket

**Comment by scye09** [comment]
Not sure if this is separate from building the table itself but we also need to be able to sort by column. Other than that, looks good!

**Comment by vanessa-hu** [comment]
I'm going to start with the first section (131-133)!
