### ISSUE TITLE
Table Edit and Delete and Save Functionality

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#131]

**Comment by vanessa-hu** [comment]
edit/delete works on front-end (fixed bug so that edit/delete also works when sorted/reordered data too, thanks melinda!)
probably going to test it with organizations to retrieve data (but will comment out parts to actually try to modify it)
in theory, I have it set up so that a prop modRoute is passed into a table, and this is the backend slug to **modify** this table. (ex: modRoute="/table")

If delete, it will send fields: 
- mode, with value "delete"
- id, with the unique row identification value

If it was an edit, it will send fields:
- mode, with value "edit"
- all fields of the object, modified (including id; done via the spread operator)

all this is commented out currently, but ideally this backend attempt will occur before modifying front-end.
