### ISSUE TITLE
Table pagination + pagination styling

### ISSUE THREAD

**Issue by crchong1** [keepid/keepid_client#145]

**Comment by vanessa-hu** [comment]
- ellipsis if > 5 items
- if on first two or last two, show both first two & last two items with ellipses in between
- if on third or third to last, show the set of three at that end, and then the last one.
- otherwise show first, ellipses, page num, ellipses, last page.
- put arrow(s) on side if not last or first page
along with #144 : can store state for results per page?

**Comment by vanessa-hu** [comment]
later styling: [custom button to get right highlight on current page num(https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Custom%20Page%20Button&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by vanessa-hu** [comment]
[fully custom info](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Fully%20Custom%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
```
const options = {
  custom: true,
  totalSize: products.length
};

class FullyCustomPagination extends React.Component {
  handleNextPage = ({
    page,
    onPageChange
  }) => () => {
    onPageChange(page + 1);
  }

  handlePrevPage = ({
    page,
    onPageChange
  }) => () => {
    onPageChange(page - 1);
  }

  handleSizePerPage = ({
    page,
    onSizePerPageChange
  }, newSizePerPage) => {
    onSizePerPageChange(newSizePerPage, page);
  }

  render() {
    return (
      <div>
        <PaginationProvider
          pagination={ paginationFactory(options) }
        >
          {
            ({
              paginationProps,
              paginationTableProps
            }) => (
              <div>
                <div>
                  <p>Current Page: { paginationProps.page }</p>
                  <p>Current SizePerPage: { paginationProps.sizePerPage }</p>
                </div>
                <div className="btn-group" role="group">
                  <button className="btn btn-primary" onClick={ this.handleNextPage(paginationProps) }>Next Page</button>
                  <button className="btn btn-success" onClick={ this.handlePrevPage(paginationProps) }>Prev Page</button>
                  <button className="btn btn-danger" onClick={ () => this.handleSizePerPage(paginationProps, 10) }>Size Per Page: 10</button>
                  <button className="btn btn-warning" onClick={ () => this.handleSizePerPage(paginationProps, 25) }>Size Per Page: 25</button>
                </div>
                <BootstrapTable
                  keyField="id"
                  data={ products }
                  columns={ columns }
                  { ...paginationTableProps }
                />
              </div>
            )
          }
        </PaginationProvider>
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
```

all options:

 ```
 paginationSize: use state??,
  pageStartIndex: 0, don't have to specify
  // alwaysShowAllBtns: false, // Always show next and previous button
  // withFirstAndLast: false, // Hide the going to First and Last page button
  // hideSizePerPage: false, // Hide the sizePerPage dropdown always
  // hidePageListOnlyOnePage: true, // Hide the pagination list when only one page
  firstPageText: 'First',
  prePageText: 'Back',
  nextPageText: 'Next',
  lastPageText: 'Last',
  nextPageTitle: 'First page',
  prePageTitle: 'Pre page',
  firstPageTitle: 'Next page',
  lastPageTitle: 'Last page',
  showTotal: true, //???
  paginationTotalRenderer: customTotal,
  disablePageTitle: true,
  sizePerPageList: [{
    text: '5', value: 5
  }, {
    text: '10', value: 10
  }, {
    text: 'All', value: products.length
  }] // A numeric array is also available. the purpose of above example is custom the text
```

**Comment by vanessa-hu** [comment]
oof... this took a long time...
wanted to leverage the TablePageSelector component that was made for the AdminPanel! so I incorporated that & modified it to fit the logic of the pagination based on the figma file (like display first 2 and last 2 if in those ranges, etc.)

So, doing remote pagination instead of the original PaginationListStandalone.
That requires me to add the "page" field to the paginationOption object that goes into paginationFactory because I'm controlling what page we're viewing based on the state called currentPage. the changeCurrentPage is a function fed to the TablePageSelector so whenever a page is changed, that updates state -> updates the _page_ value fed to the paginationFactory for the Table -> changes what the table shows. 
pageStartIndex set to 0 (default 1)
```
        const paginationOption = {
            custom: true,
            totalSize: data.length,
            paginationTotalRenderer: customTotal,
            page: currentPage, 
            pageStartIndex: 0,
            
        };
```

Also took me a while to figure out styling, so I used [this](https://stackoverflow.com/questions/32355009/changing-pagination-colour-bootstrap) and [this](https://stackoverflow.com/questions/41955791/bootstrap-pagination-css-make-border-around-thicker-but-not-the-inside-one/41955934).

I probably could have fed a React component to the options (like paginationTotalRenderer above) so I wouldn't have to do custom pagination completely, but I think it's hard to change the layout of where they are that way.
