### ISSUE TITLE
Progress bar should advance in thirds

### ISSUE THREAD

**Issue by scye09** [keepid/keepid_client#80]
If there are 3 steps to filling out the application form, the bar should start out 1/3 filled.

![image](https://user-images.githubusercontent.com/28871950/96325209-05e0fd80-0ff4-11eb-9997-8a6038ae0ae1.png)

**Comment by crchong1** [comment]
@vanessa-hu do you think u could look into this? This is ApplicationForm.tsx.

![image](https://user-images.githubusercontent.com/13875633/96819525-c9e1da00-13f1-11eb-8dae-255b5a18fb90.png)

I think you have to play around values around the aria min to make it like 1/(# of questions) instead of 0. You might just have to handle some edge cases as well, such as what if there is only 1 question or 0 questions

**Comment by vanessa-hu** [comment]
@crchong1 would you mind telling me where to see the Application Form page? tried Admin login -> black Send Application button but reaching Server Failure

**Comment by scye09** [comment]
@vanessa-hu to access this issue, you actually need to log into a client account, go to My Applicants, and then click View Application

**Comment by vanessa-hu** [comment]
Currently works / dynamically updates percentages, but eslint gives below error if I iterate over properties:
```
    for (const questionId in formAnswers) {
      if (formAnswers[questionId]) answered += 1;
    }
```
`for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array no-restricted-syntax`

But if I try iterating over entries, I get:
`iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations no-restricted-syntax`

I will try figuring this out...
